// CarComponent.idl : IDL source for CarComponent
//

// This file will be processed by the MIDL tool to
// produce the type library (CarComponent.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(a3194885-8306-4df2-ab44-abcecec6c700),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICar : IDispatch
{
};
[
	uuid(09b937df-9d93-4edb-9677-35ac8800d588),
	version(1.0),
]
library CarComponentLib
{
	importlib("stdole2.tlb");
	[
		uuid(c779aa99-9945-40b6-b144-26b1cfe0a12c)
	]
	coclass Car
	{
		[default] interface ICar;
	};
};

import "shobjidl.idl";
