#include "olectl.h"

import "oaidl.idl";
import "ocidl.idl";
import "objidl.idl";
import "wtypes.idl";

[
	object,
	uuid(1F3FCB12-5EB6-4E4F-94CF-99642FFC50C0),
	dual,
	helpstring("IEngine Interface"),
	pointer_default(unique)
]
interface IEngine : IUnknown
{
	HRESULT SpeedUp();
	HRESULT GetMaxSpeed([out] int* maxSpeed);
	HRESULT GetCurSpeed([out] int* curSpeed);
}

[
	object,
	uuid(A9490BD6-E266-411A-9511-5EC1250A3328),
	dual,
	helpstring("IStats Interface"),
	pointer_default(unique)
]
interface IStats : IUnknown
{
	HRESULT DisplayStats();
	HRESULT GetPetName([out] BSTR* petName);
}

[
	object,
	uuid(08CCACA1-3342-4689-AE23-72B6329E9FD7),
	dual,
	helpstring("ICreateCar Interface"),
	pointer_default(unique)
]
interface ICreateCar : IUnknown
{
	HRESULT SetPetName([in] BSTR maxSpeed);
	HRESULT SetMaxSpeed([in] int curSpeed);
}

[
	object,
	uuid(dda960f8-06dc-47e1-8920-6f3d7d36464d),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface ICar : IDispatch
{
};

[
	uuid(F13E8FBA-40FF-4F09-9101-314FB9C8C1DD),
	version(1.0),
	helpstring("Car Component 1.0 Type Library")
]
library CarComponent
{
	importlib("stdole2.tlb");

	[
		uuid(97B98437-966B-4F72-9527-363603BD8572),
		helpstring("Car Class"),
	]
	coclass Car
	{
		[default] interface ICar;
		interface IEngine;
		interface IStats;
		interface ICreateCar;
	}
}
